---
version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      time: '06:00'
      day: staurday
    commit-message:
      prefix: chore
      include: scope
